### ISSUE TITLE
timestamp order issue

### ISSUE THREAD

**Issue by ghost** [crypto-crawler/carbonbot#2]
file: `carbonbot/monthly/parsed/trade/2021-07/binance/spot/binance.spot.trade.BTC.USDT.BTCUSDT.2021-07.csv`

![image](https://user-images.githubusercontent.com/118121538/211124183-b5442485-e634-40cc-9e5d-728a90885bc3.png)
idx: 2880767's timestamp small than after one 2880766,
should I sort all files in timestamp before use or its some bug?

**Comment by ghost** [comment]
and seem 1hr data missing between GMT: Tuesday, July 13, 2021 1:11:53.873 AM to GMT: Tuesday, July 13, 2021 1:59:56.293 AM
![image](https://user-images.githubusercontent.com/118121538/211124752-8d7837c9-04a1-4935-a056-5a724c2c03cf.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/118121538/211125398-49e4757c-e29b-4e25-8fb4-eb44b39732d7.png)

welp, seem i better use the data before sort by trade_id, and for l2_event i should sort by timestamp at first. the original data isnt ordered well.

**Comment by soulmachine** [comment]
In the real world a message with higher `trade_id` might arrive earlier than a message with lower `trade_id`, that's why I sort messages by `timestamp` instead of `trade_id`

**Comment by ghost** [comment]
okay, but the in trade stream lots of trade has the same timestamp, in `carbonbot/monthly/parsed/trade/2021-07/binance/spot/binance.spot.trade.BTC.USDT.BTCUSDT.2021-07.csv` if use default timestamp sort in pandas some trade_id will big than prev one.

**Comment by soulmachine** [comment]
If two messages have the same `timestamp`, then we should consider `trade_id`. But not all exchanges provide `trade_id`, for example BitMEX doesn't have `trade_id`.
